# Default values for ms-htt-users.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: devhtt/ms-htt-users
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "sha-bf44fc4"

MYSQL_HOST: rds.sandbox.htt-dev-vpc.com
MYSQL_USER: htt_client
MYSQL_DATABASE: htt_client_db
MYSQLSecretName: mysql
MYSQLSecretKey: password

JWTSecretName: jwtkey
JWTSecrectKey: jwtkeyvalue
COOKIESecretName: cookiekey
COOKIESecretKey: cookiekeyvalue

OWNER_PRIV_KeyName : ownerkeysecret
OWNER_PRIV_Key : ownerkeysecretvalue

FEE_DELEGATE_PRIVE_KeyName : feepayerkeysecret
FEE_DELEGATE_PRIVE_Key : feepayerkeysecretvalue

NodeEnvValue: dev

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: app.dev.htt-wallet.io
      paths: ["/users"]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
